---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:9.2.0
  amd64: ghcr.io/hassio-addons/debian-base/amd64:9.2.0
  armv7: ghcr.io/hassio-addons/debian-base/armv7:8.1.4
  i386: ghcr.io/hassio-addons/debian-base/i386:8.1.4
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
